### ISSUE TITLE
restore env.Copy* functions

### ISSUE THREAD

**Issue by missinglink** [erigontech/mdbx-go#64]
Heya,

I'd like to have a play around with db Compaction, which was a feature I was using a bit from boltdb.
Would you consider merging a PR to uncomment the lines below, was there a reason they were commented out?

https://github.com/torquem-ch/mdbx-go/blob/f3edade9116463fb327849863a971544f9e3abf2/mdbx/env.go#L242-L276

**Comment by AskAlexSharov** [comment]
I don't remember why it commented out, just was lazy to support it and it's tests. 
Anyway can do same by `mdbx_copy -c`
